name: rootnav21
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - cython
  - imageio
  - kdtree
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pip
  - py-opencv
  - python
  - python_abi
  - pytorch
  - pytorch-mutex
  - pyyaml
  - scipy
  - tensorboardx
  - torchvision
  - tqdm
  - yaml
