                        # RootNav2 Training using Nested Hourglass
# Model Configuration
model:
    arch: Nested_HG
# Data Configuration
data:
    dataset: roots
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: /../  #path to dataset
# set batch size and number of workers
training:
    train_iters: 2500000
    batch_size: 1
    val_interval: 500
    n_workers: 12
    print_interval: 100
    # set Learning Rate and Weight Decay
    optimizer:
        name: 'rmsprop'
        lr: 1.0e-6
        weight_decay: 0.00005
        momentum: 0
    # Loss Configuration
    loss:
        name: 'cross_entropy'
        size_average: False
    # Augmentations Configuration
    augmentations:
        #rotate: 10        #[rotate -d to d degrees]
        hflip: 0.8         #[flip horizontally with chance p]
    # Transfer Leaning ... path to pre-trained model
    lr_schedule: #
    resume: #/home/usr/local/...../model.pkl 
            
        


