model:
    arch: HG
data:
    dataset: roots
    train_split: train
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: /.../ROOTS/ 
training:
    train_iters: 25000000
    batch_size: 1
    val_interval: 500
    n_workers: 1
    print_interval: 100
    optimizer:
        name: 'adam'
        lr: 0.01
        weight_decay: 0.001
        #momentum: 0.9
    loss:
        name: 'cross_entropy'
        size_average: False
    # Augmentations Configuration
    augmentations:
        #rotate: 10                                    #[rotate -d to d degrees]
        hflip: 0.6                                     #[flip horizontally with chance p]

    lr_schedule:
    resume: 


