model:
    arch: HG
data:
    dataset: roots # "roots" is currently the only dataset supported and represents image/rsml pairs
    path: ./training/data 
training:
    train_iters: 100000
    batch_size: 32
    val_interval: 100
    n_workers: 6
    print_interval: 50
    optimizer:
        lr: 1.0e-05
        momentum: 0.9
        name: rmsprop
        weight_decay: 0.001
    loss:
        name: 'dice'
        size_average: False
    # Augmentations Configuration
    augmentations:
        hflip: 0.5

    lr_schedule:
        name: multi_step
        milestones: [3500, 7000, 10500, 14000]
        gamma: 0.5
    resume: #../inference/models/wheat_bluepaper.pth
            # (can use the trained model from inference section)
testing:
    batch_size: 6
    n_workers: 6
